Repository utilForever/milky-way, pull requests merged in 2024-05, with the labels that each got.

#1 Implement base code for the game
  .gitignore
  src/app.py
  src/constants.py
  src/main.py
Labels: size/M

#2 Create a map structure
  src/camera.py
  src/constants.py
  src/map.py
  src/rect.py
Labels: size/L

#3 Create a state system
  src/app.py
  src/state.py
  src/state_machine.py
  src/state_stack.py
Labels: size/M

#4 Create an input system
  src/app.py
  src/input.py
Labels: size/M

#5 Add a state for title screen
  src/app.py
  src/play_state.py
  src/title_state.py
  src/utils.py
Labels: size/M

#7 Add resources for game
  src/app.py
  src/assets/img00.png
  src/assets/img01.png
  src/assets/img02.png
  src/assets/res.pyxres
  src/constants.py
Labels: size/S

#6 Implement text box and choice box
  src/assets/map00_spawns.csv
  src/assets/map00_tiles.csv
  src/choice_box.py
  src/panel.py
  src/text_box.py
Labels: size/XL

#8 Update README.md - add LLM Prompt
  README.md
Labels: size/L

#9 Implement utility functions to generate choices and text using LLM
  src/utils.py
Labels: size/S
